# Generated by Django 4.1.2 on 2022-10-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_rename_authors_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='time_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
